apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-abcxzy

