apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: intelligent-conference-room
  namespace: {{ .Values.global.namespace }}
spec:
  to:
    kind: Service
    name: {{ include "intelligent-conference-room.fullname" . }}
  port:
    targetPort: 5000
