apiVersion: v1
kind: Service
metadata:
  name: {{ include "intelligent-conference-room.fullname" . }}
  labels:
    {{- include "intelligent-conference-room.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "intelligent-conference-room.selectorLabels" . | nindent 4 }}
